Courses/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.courses.urls', namespace='courses'))
]

apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add$', views.add, name="add"),
    url(r'^destroy/(?P<id>[0-9]+)$', views.destroy, name="destroy"),
    url(r'^destroy_really/(?P<id>[0-9]+)$', views.destroy_really, name="destroy_really")
]

apps/courses/models.py
from __future__ import unicode_literals
from django.db import models

class CourseManager(models.Manager):
    def basic_validator(self, post_data):
        errors = {}
        if len(post_data['name']) <= 10:
            errors['name'] = 'Course name must be more than 10 characters'
        if len(post_data['description']) <= 15:
            errors['description'] = 'Course description must be greater than 15 characters'
        return errors

class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CourseManager()
    def __repr__(self):
        return "<Course object: {}>".format(self.name)

apps/courses/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse

from .models import Course

def index(request):
    context = {"courses": []}
    courses = Course.objects.all()
    for course in courses:
        context['courses'].append({
            "id": course.id,
            "name": course.name,
            "description": course.description,
            "date_added": course.created_at.strftime('%B %e %Y %l:%M%p')
        })
    return render(request, 'courses/index.html', context)

def add(request):
    if request.method == 'POST':

        # FORM VALIDATION
        errors = Course.objects.basic_validator(request.POST)
        if len(errors):
            for tag, error in errors.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect(reverse('courses:index'))

        # ADD TO DATABASE
        Course.objects.create(name=request.POST['name'], description=request.POST['description'])

        return redirect(reverse('courses:index'))
    else:
        return redirect(reverse('courses:index'))

def destroy(request, id):
    course = Course.objects.get(id=id)
    context = {
        "id": course.id,
        "name": course.name,
        "description": course.description
    }
    return render(request, 'courses/destroy.html', context)

def destroy_really(request, id):
    if request.method == "POST":
        Course.objects.get(id=id).delete()
        return redirect(reverse('courses:index'))
    else:
        return redirect(reverse('courses:index'))

apps/courses/templates/courses/destroy.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Delete a course</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body {
                font-family: arial, sans-serif;
            }
            form {
                display: inline;
            }
            input {
                background-color: red;
                color: white;
            }
        </style>
    </head>
    <body>
        <h1>Are you sure you want to delete the following course?</h1>
        <p>Name: {{name}}</p>
        <p>Description: {{description}}</p>
        <a href={% url 'courses:index' %}><button type="button">No</button></a> 
        <form action={% url 'courses:destroy_really' id=id %} method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes! I want to delete this!">
        </form>
    </body>
</html>

apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Courses</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body {
                font-family: arial, sans-serif;
            }

            table {
                border-collapse: collapse;
                width: 100%;
            }

            td, th {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }
        </style>
    </head>
    <body>
        {% if messages %}
        <div style="color:red;">
            <h3>ERRORS:</h3>
            <ul>
                {% for message in messages %}
                <li>{{message}}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <h1>Add a new course</h1>
        <form action={% url 'courses:add' %} method="POST">
            {% csrf_token %}
            <label for="name">Name: </label><br>
            <input type="text" name="name" id="name">
            <br><br>
            <label for="description">Description: </label><br>
            <input type="text" name="description" id="description">
            <br><br>
            <input type="submit" value="Add">
        </form>
        {% if courses %}
            <h1>Courses</h1>
            <table>
                <tr>
                    <th>Course Name</th>
                    <th>Description</th>
                    <th>Date Added</th>
                    <th>Actions</th>
                </tr>
                {% for course in courses %}
                <tr>
                    <td>{{course.name}}</td>
                    <td>{{course.description}}</td>
                    <td>{{course.date_added}}</td>
                    <td><a href={% url 'courses:destroy' id=course.id %}>remove</a></td>
                </tr>
                {% endfor %}
            </table>
        {% endif %}
    </body>
</html>